### ISSUE TITLE
 I am unable to clone the pwc_net_ros package

### ISSUE THREAD

**Issue by yimengweima0** [VisualComputingInstitute/CROWDBOT_perception#1]
Thank you so much for open-sourcing the code. However, when I attempted to clone and modify it, I encountered an issue with cloning the pwc_net_ros package. It seems that it requires a password from git@git.rwth-aachen.de.

**Comment by Pandoro** [comment]
@kumuji @sabarim could you have a look at this?

**Comment by sabarim** [comment]
@yimengweima0 can you try this again now?

**Comment by yimengweima0** [comment]
> @yimengweima0 can you try this again now?

yeah, I just tried it, but I still encountered the same problem. Here is my screenshot.
![2023091809⁄18⁄23](https://github.com/VisualComputingInstitute/CROWDBOT_perception/assets/50518889/8ab5fa98-749d-4b9b-bb67-ba56e550b683)

**Comment by yimengweima0** [comment]
> @yimengweima0 can you try this again now?

I suspect that the main reason is that the "pwc_net_ros" repository is private. Could you please make the "pwc_net_ros" repository public?

**Comment by yimengweima0** [comment]
I suspect that the main reason is that the "pwc_net_ros" repository is private. Could you please make the "pwc_net_ros" repository public? @sabarim

**Comment by yimengweima0** [comment]
> @kumuji @sabarim could you have a look at this?
@Pandoro  I  suspect that the main reason is that the "pwc_net_ros" repository is private. Could you please make the "pwc_net_ros" repository public?  Thank you very much.

**Comment by Pandoro** [comment]
It has been made public already. The problem is that the module still tries
to checkout via ssh. Just modify the .gitmodules file to use a https link.
It should be:

https://git.rwth-aachen.de/sabarinath.mahadevan/pwc_net_ros.git

**Comment by yimengweima0** [comment]
Thanks you very much.
